name: Release
on:
  push:
    branches:
      - master

jobs:

  gdal:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack:
          - name: heroku-16
            image: heroku/heroku:16-build
          - name: heroku-18
            image: heroku/heroku:18-build
        version:
          - 2.4.0
          - 2.4.2
    container: ${{ matrix.stack.image }}
    steps:
      - uses: actions/checkout@v2
      - run: apt-get -q update && apt-get -q -y --no-install-recommends install awscli
      - run: ./builds/gdal/gdal-${{ matrix.version }}.sh
        env:
          STACK: ${{ matrix.stack.name }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  geos:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack:
          - name: heroku-16
            image: heroku/heroku:16-build
          - name: heroku-18
            image: heroku/heroku:18-build
        version:
          - 3.7.2
    container: ${{ matrix.stack.image }}
    steps:
      - uses: actions/checkout@v2
      - run: apt-get -q update && apt-get -q -y --no-install-recommends install awscli
      - run: ./builds/geos/geos-${{ matrix.version }}.sh
        env:
          STACK: ${{ matrix.stack.name }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  proj:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack:
          - name: heroku-16
            image: heroku/heroku:16-build
          - name: heroku-18
            image: heroku/heroku:18-build
        version:
          - 5.2.0
    container: ${{ matrix.stack.image }}
    steps:
      - uses: actions/checkout@v2
      - run: apt-get -q update && apt-get -q -y --no-install-recommends install awscli
      - run: ./builds/proj/proj-${{ matrix.version }}.sh
        env:
          STACK: ${{ matrix.stack.name }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
